### ISSUE TITLE
Transparency issues with embedium mod.

### ISSUE THREAD

**Issue by Aer-ink** [MoreMcmeta/emissive-plugin#6] opened 2023-10-02 17:31 UTC
**Describe the bug**
Transparency issues with "plant" blocks near or in water when embedium is in the same instance.

**To reproduce**
just get near kelp or any plant near water.

**Screenshots or videos**
![2023-10-02_12 17 48](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/acd30222-21c0-45e8-a51f-93dad98b7e7f)
![2023-10-02_12 18 11](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/73a575b5-054f-420a-9b71-0bbc2f7611b7)
![2023-10-02_12 18 51](https://github.com/MoreMcmeta/emissive-plugin/assets/19780430/99253dc6-0e62-401e-9b96-a27bf6b1750b)

**Which Minecraft versions does this bug affect?**
Tested in 1.18.2

**Mod loader**
Which mod loaders does this bug affect?
[ ] Forge v 40.2.5

**Mods list**
moremcmeta-1.18.2-4.2.4-forge
emissive-plugin-1.18.2-1.1.1-forge
textrues_embeddium_options-0.1.1+mc1.18.2
embeddium-0.1.14+mc1.18.2

**Comment by soir20** [comment] 2023-10-02 18:53
Thanks for reporting. This looks like a duplicate of #5, which is caused by Sodium and its ports incorrectly ordering translucent faces. I'll take a closer look in a few hours to make sure that's the case before closing as a duplicate.

I have some early plans for a v2 of this mod where overlays will not support translucence by default, but you can enable it on a per-overlay basis. That would help with a lot of these compatibility issues related to the translucent rendering this mod uses, since almost all existing emissive packs don't need partial transparency. I don't have an ETA on that as it's still in a planning phase.

**Comment by soir20** [comment] 2023-10-03 03:07
I've confirmed that Embeddium has the same translucent sorting issue as Sodium, so I'm closing this as a duplicate of #5. However, I did notice that this doesn't happen on 1.19.2+ if you are able to update your Minecraft version.

**Closed as not planned by soir20** 2023-10-03 03:07 UTC
Labels: type: bug, status: duplicate, mc: 1.18.x, mc: 1.17.x, mc: 1.16.x, loader: forge, compatibility
