### ISSUE TITLE
incompatible with Rubidium.

### ISSUE THREAD

**Issue by ghost** [MoreMcmeta/emissive-plugin#2] opened 2023-07-20 13:20 UTC
**Describe the bug**
This mod will become ineffective when working with Rubidium

**Expected behavior**
![2023-07-20_21 17 44](https://github.com/MoreMcmeta/emissive-plugin/assets/129179911/136e9e7c-9f6a-4d01-a190-8ec9e663c5bf)
(without rubidium)

**Screenshots or videos**
![2023-07-20_21 16 23](https://github.com/MoreMcmeta/emissive-plugin/assets/129179911/0d69eb82-f2aa-4bde-b9a1-a25b0f51e781)
(with rubidium)

**Which Minecraft versions does this bug affect?**
1.19.2

**Mod loader**
Which mod loaders does this bug affect?
1.19.2-Forge_43.2.21

**Mods list**
rubidium-0.6.2b
moremcmeta-1.19.2-4.0.1-forge
emissive-plugin-1.19.2-1.0.1-forge

**Resource pack**
What resource packs are you using? Please link to them or attach them to this issue.
https://www.curseforge.com/minecraft/texture-packs/emissive-txf/

**Comment by soir20** [comment] 2023-07-20 22:06
Thanks for reporting. I'm looking into this.

Notes for my own investigation into the issue:

**Affected items**
* Block overlays (emissivity only in 1.19.2+, all overlays in <=1.18)
* Enderman block overlays (emissivity only)
* Snow Golem head overlays (emissivity only)

**Unaffected items**
* Entities
* Block entities

Pre-1.19 versions are also affected.

**Comment by soir20** [comment] 2023-07-20 23:42
This looks like an issue with Rubidium ignoring per-vertex lighting data. I don't see a way for MoreMcmeta to fix the incompatibility without making more invasive changes to the game's code, which would likely cause problems with other mods.

It seems like an easier fix on Rubidium's end (from my relatively brief look through their code). They would probably want to fix it anyway since it could create issues with other mods. Hence, I'm going to open up an issue in Rubidium's repository and link it here.

**Comment by soir20** [comment] 2023-07-21 02:06
I've opened an issue in Rubidium's repository: Asek3/Rubidium#539. I recommend "subscribing" to the issue so that you get notifications when there are replies.

I'm going to mark this issue as transferred and close it since I currently don't plan to fix it on my end. Please feel free to reopen this issue if new information arises, or if a non-invasive solution for MoreMcmeta to implement is found.

**Closed as not planned by soir20** 2023-07-21 02:06 UTC
Labels: type: bug, status: transferred, mc: 1.20.x, mc: 1.19.x, mc: 1.18.x, mc: 1.17.x, mc: 1.16.x, loader: forge, compatibility

**Comment by ghost** [comment] 2023-07-21 07:58
I have discovered the same issue on fabric caused by sodium.It should be sodium's problem and rubidium inherited it.Could you open up a new issue in their issue tracker?Because I don't understand all the technicalities.

**Comment by soir20** [comment] 2023-07-21 14:38
Are you using Indium with Sodium on Fabric? MoreMcmeta uses the Fabric rendering API, so Indium is required to support that.

It looks like the issue will need to be transferred to Sodium anyway (see the discussion on the Rubidium issue).

**Comment by ghost** [comment] 2023-07-21 17:30
> ee the discussion on the Rubidium issue).

No.I didn't use Indium when I was testing.Everything works well when Indium installed.It seems to be rubidium's problem.

The author of Rubidium also ported Fabric rendering API and Indium to Forge [Reforgium](https://www.curseforge.com/minecraft/mc-mods/reforgium).I'm not sure if it is helpful to make emissive plugin compatible with rubidium

**Comment by soir20** [comment] 2023-07-21 18:45
The underlying bug is likely an issue with both Rubidium and Sodium, just that Indium basically masks the issue when you're using Sodium. I'll need to double check Sodium's code to confirm and then create an issue over there.

**Comment by soir20** [comment] 2023-07-21 19:47
> The author of Rubidium also ported Fabric rendering API and Indium to Forge [Reforgium](https://www.curseforge.com/minecraft/mc-mods/reforgium).I'm not sure if it is helpful to make emissive plugin compatible with rubidium

I'll look into this, but if it works like the Fabric API, then everyone who wants to use this emissive plugin would have to download Reforgium. Since it is not widely used like the Fabric API is, and the Fabric API modifies a good portion of Minecraft's rendering, it might cause more compatibility issues.

EDIT: This would not work if there is no Indium equivalent on Forge because Sodium, and presumably Rubidium, do not support the Fabric API by themselves.

**Comment by ghost** [comment] 2023-07-22 05:15
> > The author of Rubidium also ported Fabric rendering API and Indium to Forge [Reforgium](https://www.curseforge.com/minecraft/mc-mods/reforgium).I'm not sure if it is helpful to make emissive plugin compatible with rubidium
> 
> I'll look into this, but if it works like the Fabric API, then everyone who wants to use this emissive plugin would have to download Reforgium. Since it is not widely used like the Fabric API is, and the Fabric API modifies a good portion of Minecraft's rendering, it might cause more compatibility issues.
> 
> EDIT: This would not work if there is no Indium equivalent on Forge because Sodium, and presumably Rubidium, do not support the Fabric API by themselves.

I also suppose depending on Reforgium to bypass this issue is not a good choice.The problem should be tackled at the root.Thank you for your efforts!

**Comment by soir20** [comment] 2023-07-22 05:39
It looks like the per-vertex lighting is a feature Forge patched into the vanilla code. Hence, I won't be reporting this to Sodium, since the patch wouldn't be present on Fabric.

> I also suppose depending on Reforgium to bypass this issue is not a good choice.

Even though the issue is technically isolated to Forge, using Reforgium would likely cause problems with a lot of other mods. The Fabric API basically rewrites a good portion of block rendering. Including Reforgium to fix this compatibility issue would likely cause compatibility problems with other mods that depend on regular vanilla block rendering + Forge's patches. These types of mods aren't uncommon, probably more common than Rubidium is.

**Comment by ghost** [comment] 2023-09-25 16:40
![2023-09-26_00 38 53](https://github.com/MoreMcmeta/emissive-plugin/assets/129179911/6289105a-ceb9-4010-b60f-d91371b9bbb3)
Seems to be fixed in rubidium-mc1.19.2-0.6.2c
