### ISSUE TITLE
beacon rays crashes the game

### ISSUE THREAD

**Issue by dablioz** [MoreMcmeta/emissive-plugin#26] opened 2024-09-11 15:17 UTC
**Describe the bug**
when the game tries to render a beacon ray, it crashes

**To reproduce**
1. build a functional beacon
2. game crashes

**Which Minecraft versions does this bug affect?**
List Minecraft versions that this bug affects.
Tested on 1.21.1

**Mod loader**
Which mod loaders does this bug affect?
- [ ] Forge
- [ X ] Fabric

**Mods list**
sodium
indium
moremc meta
moremc emmissive textures

**Additional context**
Crash Log:
https://mclo.gs/zDIf6ei

**Comment by soir20** [comment] 2024-09-16 06:08
Thanks for providing detailed logs; this is a duplicate of #27 and is a compatibility issue with Sodium 0.6. I'll close this in favor of the existing issue. I believe you can use an earlier Sodium version to avoid the crash in the meantime.

**Closed as not planned by soir20** 2024-09-16 06:08 UTC
Labels: type: bug, status: duplicate, loader: fabric, compatibility, mc: 1.21.x
